### ISSUE TITLE
Unable to add accessories

### ISSUE THREAD

**Issue by cheng5230** [ambiot/ambd_matter#123]
ATM$
xPortGetTotalHeapSize = 204800 
xPortGetFreeHeapSize = 44800 
xPortGetMinimumEverFreeHeapSize = 36448 
[_dct_init_valid_module]: erase flash address 0x001cc000
[_dct_init_valid_module]: erase flash address 0x001cd000
[_dct_init_valid_module]: erase flash address 0x001ce000
[_dct_init_valid_module]: erase flash address 0x001cf000
[_dct_init_valid_module]: erase flash address 0x001d0000
[_dct_init_valid_module]: erase flash address 0x001d1000
[_dct_init_valid_module]: erase flash address 0x001d2000
[_dct_init_valid_module]: erase flash address 0x001d3000
[_dct_init_valid_module]: erase flash address 0x001d4000
[_dct_init_valid_module]: erase flash address 0x001d5000
[_dct_init_valid_module]: erase flash address 0x001d6000
[_dct_init_valid_module]: erase flash address 0x001d7000
[_dct_init_valid_module]: erase flash address 0x001d8000
[dct_format]: DCT format success, please do dct_init() again.
dct_format success
[_dct_init_valid_module]: erase flash address 0x003b6000
[_dct_init_valid_module]: erase flash address 0x003b7000
[_dct_init_valid_module]: erase flash address 0x003b8000
[_dct_init_valid_module]: erase flash address 0x003b9000
[_dct_init_valid_module]: erase flash address 0x003ba000
[_dct_init_valid_module]: erase flash address 0x003bb000
[dct_format2]: DCT format success, please do dct_init() again.
dct_format2 success
[ATM$]: _AT_SYSTEM_TEST_

[MEM] After do cmd, available heap 45184

#
#calibration_ok:[2:19:11] 
#
interface 0 is initialized
interface 1 is initialized

Initializing WIFI ...
WIFI initialized

init_thread(58), Available heap 0x17560chip[DL] Lighting example!

dct_init success
dct_init2 success
dct_register_module matter_kvs1_1 success
dct_register_module matter_kvs1_2 success
dct_register_module matter_kvs1_3 success
dct_register_module matter_kvs1_4 success
dct_register_module matter_kvs1_5 success
dct_register_module matter_kvs1_6 success
dct_register_module matter_kvs1_7 success
dct_register_module matter_kvs1_8 success
dct_register_module matter_kvs1_9 success
dct_register_module matter_kvs1_10 success
dct_register_module matter_kvs1_11 success
dct_register_module matter_kvs1_12 success
dct_register_module matter_kvs1_13 success
dct_register_module2 matter_kvs2_1 success
dct_register_module2 matter_kvs2_2 success
dct_register_module2 matter_kvs2_3 success
dct_register_module2 matter_kvs2_4 success
dct_register_module2 matter_kvs2_5 success
dct_register_module2 matter_kvs2_6 success
chip[DL] NVS set: chip-counters/reboot-count = 1 (0x1)
chip[DL] NVS set: chip-counters/total-hours = 0 (0x0)
chip[DL] NVS set: chip-counters/boot-reason = 0 (0x0)
chip[DL] NVS set: chip-config/regulatory-location = 0 (0x0)
chip[DL] NVS set: chip-config/location-capability = 2 (0x2)
chip[DL] getPref_str_new: chip-factory/uniqueId failed

chip[DL] NVS set: chip-factory/uniqueId = "C5C3BF3885303B4B"

BT BUILD Date: 2024/06/05-19:58:38 
BT Reset...
bd addr: f2:d6:42:3f:bf:0e

[BT Config Wifi] bt_matter_adapter_app_task_init
physical efuse: has data hci_tp_phy_efuse[1]= 9e 

hci_tp_phy_efuse[0]=0,
bt_iqk_dump:    DUMP,
the IQK_xx  data is 0x114,
the IQK_yy  data is 0x5,
the QDAC  data is 0x25,
the IDAC  data is 0x1f,
hci_read_rom_check: rom_version 0x0002, bt_hci_chip_id 0x0003

BT ADDRESS: c4:e5:b1:10:06:05

 WRITE  physical FLATK=tx_flatk=ff 
Set baudrate to 921600

hci_tp_config:BT INIT success 7
Start upperStack
chip_blemgr_callback_func is NULL
chip_blemgr_callback_func is NULL
DecodeFactory 1 
dac_key 510 
dac_cert 32 
cd 242 
chip[DL] FactoryData of length: 1590 retrieved successfully
chip[DL] Started BLE Advertising
chip[DL] Long dispatch time: 105 ms, for event type 2

WIFI Mode No Need To Change: STA -->STAchip[DL] Done driving station state, nothing else to do...
chip[SVR] Subscription persistence not supported
chip[SVR] Server initializing...
chip[TS] Last Known Good Time: [unknown]
chip[TS] Setting Last Known Good Time to firmware build time 2023-10-14T01:16:48
chip[DMG] AccessControl: initializing
chip[DMG] Examples::AccessControlDelegate::Init
chip[DMG] AccessControl: setting
chip[DMG] DefaultAclStorage: initializing
chip[DMG] DefaultAclStorage: 0 entries loaded
chip[ZCL] Using ZAP configuration...
chip[DMG] AccessControlCluster: initializing
chip[ZCL] Initiating Admin Commissioning cluster.
chip[ZCL] DeviceInfoProvider is not registered
chip[DL] Uplink Event Queue is NULL should never happen
chip[DL] Uplink Event Queue is NULL should never happen
chip[DL] Uplink Event Queue is NULL should never happen
chip[ZCL] Endpoint 1 On/off already set to new value
chip[DL] Uplink Event Queue is NULL should never happen
chip[DL] Uplink Event Queue is NULL should never happen
chip[DL] Uplink Event Queue is NULL should never happen
chip[DL] Uplink Event Queue is NULL should never happen
chip[DL] Uplink Event Queue is NULL should never happen
chip[DIS] Updating services using commissioning mode 1
chip[DIS] CHIP minimal mDNS started advertising.
chip[DIS] Advertise commission parameter vendorID=5124 productID=4096 discriminator=1718/06 cm=1 cp=0
chip[DIS] CHIP minimal mDNS configured as 'Commissionable node device'; instance name: EE434999B5111C53.
chip[DIS] mDNS service published: _matterc._udp
chip[IN] CASE Server enabling CASE session setups
chip[SVR] Joining Multicast groups
chip[SVR] Server Listening...
chip[SVR] SetupQRCode: [MT:SES00UDN16YKLH7JD10]
chip[SVR] Copy/paste the below URL in a browser to see the QR Code:
chip[SVR] https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3ASES00UDN16YKLH7JD10
chip[SVR] Manual pairing code: [14677439154]
chip[DL] Long dispatch time: 247 ms, for event type 2
chip[Dchip[DL] UpL] Uplink Talink Task ssk started
tarted

chip[DL] Started BLE Advertising
chip[DL] Long dispatch time: 104 ms, for event type 2
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[BLE] local and remote recv window sizes = 5
chip[BLE] selected BTP version 4
chip[BLE] using BTP fragment sizes rx 244 / tx 244.
chip[DL] CHIPoBLE subscribe received
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[EM] >>> [E:30999r S:0 M:728744] (U) Msg RX from 0:C7DCAFFE8DDAF23A [0000] --- Type 0000:20 (SecureChannel:PBKDFParamRequest)
chip[EM] <<< [E:30999r S:0 M:110750857] (U) Msg TX to 0:0000000000000000 [0000] [BLE] --- Type 0000:21 (SecureChannel:PBKDFParamResponse)
chip[SVR] Commissioning session establishment step started
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[EM] >>> [E:30999r S:0 M:728745] (U) Msg RX from 0:C7DCAFFE8DDAF23A [0000] --- Type 0000:22 (SecureChannel:PASE_Pake1)
chip[EM] <<< [E:30999r S:0 M:110750858] (U) Msg TX to 0:0000000000000000 [0000] [BLE] --- Type 0000:23 (SecureChannel:PASE_Pake2)
chip[DL] Long dispatch time: 482 ms, for event type 7
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[EM] >>> [E:30999r S:0 M:728746] (U) Msg RX from 0:C7DCAFFE8DDAF23A [0000] --- Type 0000:24 (SecureChannel:PASE_Pake3)
chip[EM] <<< [E:30999r S:0 M:110750859] (U) Msg TX to 0:0000000000000000 [0000] [BLE] --- Type 0000:40 (SecureChannel:StatusReport)
chip[SC] SecureSession[0x1002ee68, LSID:26403]: State change 'kEstablishing' --> 'kActive'
chip[SVR] Commissioning completed session establishment step
chip[DIS] Updating services using commissioning mode 0
chip[DIS] CHIP minimal mDNS started advertising.
chip[SVR] Device completed Rendezvous process
chip[DL] CHIPoBLE advertising stopped
chip[DL] Stopped BLE Advertising
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[EM] >>> [E:31000r S:26403 M:4374231] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:02 (IM:ReadRequest)
chip[EM] <<< [E:31000r S:26403 M:150393409] (S) Msg TX to 0:FFFFFFFB00000000 [0000] [BLE] --- Type 0001:05 (IM:ReportData)
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[EM] >>> [E:31001r S:26403 M:4374232] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:02 (IM:ReadRequest)
chip[EM] <<< [E:31001r S:26403 M:150393410] (S) Msg TX to 0:FFFFFFFB00000000 [0000] [BLE] --- Type 0001:05 (IM:ReportData)
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[EM] >>> [E:31002r S:26403 M:4374233] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:02 (IM:ReadRequest)
chip[EM] <<< [E:31002r S:26403 M:150393411] (S) Msg TX to 0:FFFFFFFB00000000 [0000] [BLE] --- Type 0001:05 (IM:ReportData)
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[EM] >>> [E:31003r S:26403 M:4374234] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:02 (IM:ReadRequest)
chip[EM] <<< [E:31003r S:26403 M:150393412] (S) Msg TX to 0:FFFFFFFB00000000 [0000] [BLE] --- Type 0001:05 (IM:ReportData)
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[EM] >>> [E:31004r S:26403 M:4374235] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:02 (IM:ReadRequest)
chip[EM] <<< [E:31004r S:26403 M:150393413] (S) Msg TX to 0:FFFFFFFB00000000 [0000] [BLE] --- Type 0001:05 (IM:ReportData)
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[EM] >>> [E:31005r S:26403 M:4374236] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
1        Infra   24:cf:24:e2:80:ad -24    1        6      WPA2 AES                FTY_RD 
2        Infra   a4:39:b3:08:7c:f8 -43    6        7      WPA2 AES                Xiaomi_router 
3        Infra   f8:3e:95:b1:4e:70 -46    60       6      WPA/WPA2 Mixed                  FTY 
4        Infra   f8:3e:95:b1:4e:71 -46    60       6      WPA/WPA2 Mixed                  FTY_GUEST 
5        Infra   bc:54:fc:c2:d0:16 -49    12       6      WPA/WPA2 AES            Diro 
6        Infra   02:b8:17:c9:26:5b -50    44       7      WPA2 AES                HUAWEI-1B9D5H_5G 
7        Infra   a4:39:b3:08:7c:f7 -50    44       7      WPA2 AES                Xiaomi_router_5G 
8        Infra   d4:da:21:74:24:4c -53    9        7      WPA2 AES                国鑫恒运 
9        Infra   5c:02:14:76:ea:77 -55    6        7      WPA2 AES                Redmi_kao 
10       Infra   5c:02:14:76:ea:76 -57    48       7      WPA2 AES                Redmi_kao_5G 
11       Infra   f8:3e:95:b1:4e:61 -58    11       6      WPA/WPA2 Mixed                  FTY_GUEST 
12       Infra   f8:3e:95:b1:4e:60 -59    11       6      WPA/WPA2 Mixed                  FTY 
13       Infra   f8:3e:95:b1:03:90 -59    56       6      WPA/WPA2 Mixed                  FTY 
14       Infra   f8:3e:95:b1:03:91 -59    56       6      WPA/WPA2 Mixed                  FTY_GUEST 
15       Infra   d4:da:21:74:24:4d -64    157      7      WPA2 AES                国鑫恒运 
16       Infra   f8:3e:95:b1:03:80 -66    11       6      WPA/WPA2 Mixed                  FTY 
17       Infra   f8:3e:95:b1:35:90 -66    52       6      WPA/WPA2 Mixed                  FTY 
18       Infra   68:dd:b7:c4:84:34 -66    157      6      WPA/WPA2 AES            TP-LINK_5G_8432 
19       Infra   f8:3e:95:b1:35:91 -67    52       6      WPA/WPA2 Mixed                  FTY_GUEST 
20       Infra   60:01:95:10:71:78 -68    1        6      Open            SmartLife-7178 
21       Infra   f8:3e:95:b0:ff:b0 -68    48       6      WPA/WPA2 Mixed                  FTY 
22       Infra   f8:3e:95:b1:4f:70 -69    40       6      WPA/WPA2 Mixed                  FTY 
23       Infra   f8:3e:95:b1:4f:71 -69    40       6      WPA/WPA2 Mixed                  FTY_GUEST 
24       Infra   f8:3e:95:b1:35:80 -70    1        6      WPA/WPA2 Mixed                  FTY 
25       Infra   f8:3e:95:b1:35:81 -70    1        6      WPA/WPA2 Mixed                  FTY_GUEST 
26       Infra   f8:3e:95:b0:ff:b1 -70    48       6      WPA/WPA2 Mixed                  FTY_GUEST 
27       Infra   64:64:4a:9c:af:02 -71    36       7      WPA2 AES                Redmi_1111_5G 
28       Infra   a4:56:02:a6:bb:31 -80    6        6      WPA/WPA2 AES            U-GEN-605-2.4G 
29       Infra   f8:3e:95:b1:31:b1 -80    161      6      WPA/WPA2 Mixed                  FTY_GUEST 
30       Infra   f8:3e:95:b1:02:b0 -81    36       6      WPA/WPA2 Mixed                  FTY 
31       Infra   f8:3e:95:b1:31:b0 -81    161      6      WPA/WPA2 Mixed                  FTY 
32       Infra   f8:3e:95:b1:02:b1 -82    36       6      WPA/WPA2 Mixed                  FTY_GUEST 
33       Infra   2c:c5:46:f1:56:22 -86    149      6      WPA2 AES                HUAWEI-H108ZC_Wi-Fi5 
34       Infra   d0:c7:c0:4e:4e:24 -87    6        7      Open            FTY-007 
35       Infra   2c:c5:46:31:56:20 -87    149      7      WPA2 AES                HUAWEI-H108ZC 
36       Infra   9c:21:6a:0d:95:d0 -88    11       7      WPA/WPA2 AES            TP-LINK_0D95D0 
chip[DL] WiFiScanCompleted
chip[DL] ScheduleLambda OK
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEWriteReceived
chip[DL] _OnPlatformEvent kCHIPoBLEIndicateConfirm
chip[DL] _OnPlatformEvent kCHIPoBLEConnectionError
chip[BLE] Releasing end point's BLE connection back to application.
chip[FS] Fail-safe timer expired
chip[SVR] Failsafe timer expired
chip[SC] SecureSession[0x1002ee68, LSID:26403]: State change 'kActive' --> 'kPendingEviction'
chip[SVR] Commissioning failed (attempt 1): 32
chip[DIS] Updating services using commissioning mode 1
chip[DIS] CHIP minimal mDNS started advertising.
chip[DIS] Advertise commission parameter vendorID=5124 productID=4096 discriminator=1718/06 cm=1 cp=0
chip[DIS] CHIP minimal mDNS configured as 'Commissionable node device'; instance name: EE434999B5111C53.
chip[DIS] mDNS service published: _matterc._udp
chip[DMG] Failed to finalize command response: 3
chip[DMG] Failed to send InvokeResponseMessage
chip[ZCL] OpCreds: Got FailSafeTimerExpired
chip[ZCL] OpCreds: Proceeding to FailSafeCleanup on fail-safe expiry!
chip[TS] Pending Last Known Good Time: 2023-10-14T01:16:48
chip[TS] Previous Last Known Good Time: 2023-10-14T01:16:48
chip[TS] Reverted Last Known Good Time to previous value
chip[FS] Fail-safe cleanly disarmed
chip[DL] Started BLE Advertising
chip[DL] Long dispatch time: 105 ms, for event type 2
chip[DL] Started BLE Advertising
chip[DL] Long dispatch time: 104 ms, for event type 2

**Comment by xshuqun** [comment]
@cheng5230 could you try to cherry-pick this [commit](https://github.com/project-chip/connectedhomeip/pull/33629) to your local sdk and rebuild the sdk for test?

**Comment by cheng5230** [comment]
@xshuqun  thanks 

> @cheng5230 could you try to cherry-pick this [commit](https://github.com/project-chip/connectedhomeip/pull/33629) to your local sdk and rebuild the sdk for test?
