### ISSUE TITLE
[Not an Issue!] SmokeCOAalarm device : any example ?

### ISSUE THREAD

**Issue by chinfu** [ambiot/ambd_matter#127]
Dear,
I am trying to hooking a non-matter/battery-powered SmokeCOAlarm device to the bridge_dm example.
First, is there any reference for the normal "SmokeCOAlarm" device ?

Thank you !

BR,
Vic

**Comment by xshuqun** [comment]
Dear @chinfu ,
we did test out the SmokeCOAlarm cluster, have added some of the functions in the following links

- https://github.com/project-chip/connectedhomeip/blob/master/examples/all-clusters-app/ameba/main/SmokeCOAlarmManager.cpp
- https://github.com/project-chip/connectedhomeip/blob/master/examples/all-clusters-app/ameba/main/chipinterface.cpp#L185

You will need the sTestEventTriggerEnableKey to be set to support this cluster.
However, these implementation has not been added into the porting layer. You can give it a try, and do let me know if there is any problem.

And regarding the bridge issue in #104 , for now you can remove the Bridged Node device type and work with it. Once I have figured out the issue, I will update you!

Thank you

**Comment by chinfu** [comment]
Dear @xshuqun ,
It is great to hear that. I'll try it....
Thank you.

BR,
Vic

**Comment by chinfu** [comment]
Dear @xshuqun ,
I am curious about the behavior of the SmokeCOAlarm device on the GoogleHomeApp.
Do you have any experience on this ?

For trying SmokeCOAlarm:
1. I try to use the MatterVirtualDevice.
2. commit it into my Google Nest.
3. I can see the device on the GoogleHomeApp.
4. **But, while I am trying all the alert message on the MVD, there is not any message/notifaction on the GHA. Is this nomal behavior for this kind of alarm device ?**.   ( I "think/guess", after the alarm device fires some alert messages, the GHA should pop some notifications.)
( by using light/plug-in device on the MVD, the MVD works well with the GHA)
<img width="367" alt="mvd" src="https://github.com/ambiot/ambd_matter/assets/9313557/7448e241-d83d-4cb6-a448-f17856d8519e">

Thank you !
BR,
VIc

**Comment by xshuqun** [comment]
@chinfu I have never tried on this before. As this device is not officially supported by Google yet, i doubt that the functions are all working well.
If this is urgent on your side, maybe you could approach Google Help Desk to ask for details?

**Comment by chinfu** [comment]
Dear @xshuqun ,
Rogee that.
I had tried to file this as an issue to Google.
Thanks .

Br,
Vic

**Comment by chinfu** [comment]
Dear @xshuqun,

I was hoping you could assist with a few quick questions:

Using the bridge_dm example, how many bridged devices can be attached to this bridge? From my testing, it seems I can only attach around 11 devices.

Regarding the Google Home App (GHA), is there a method or path for the bridge to set or read the name and location of each bridged device within the GHA? Specifically, if a user changes a device's name or location in the GHA, is there a way for our private app/tool to sync with these updates?

Thank you!

![Screenshot_20240731_134042_Home](https://github.com/user-attachments/assets/9f257d84-04f8-42f6-be8d-651a4fdde279)

BR,
Vic
