### ISSUE TITLE
[wifi] error not utilized in matter_wifi_connect

### ISSUE THREAD

**Issue by step0035** [ambiot/ambd_matter#77]
- in `matter_wifis.c`, look for `matter_wifi_connect`, the `err = 0` is useless
- the `err` should be assigned the return value of the `wifi_connect` function
- return value of `matter_wifi_connect` should not be hardcoded to `RTW_SUCCESS`

**Comment by SirRu24** [comment]
No need to change based on PR #78 comment by Shu Qun
