### ISSUE TITLE
[Request] Add Matter factory reset example

### ISSUE THREAD

**Issue by jackhax1** [ambiot/ambd_matter#86]
Kindly please add factory reset feature in order to remove all saved fabric and wifi credentials

**Comment by xshuqun** [comment]
@jackhax1 Sorry for the late response. Apparently we are using at commands ATM$ to perform factory reset 
You can checkout the api here https://github.com/ambiot/ambd_matter/blob/main/component/common/application/matter/common/atcmd/atcmd_matter.c#L18

**Comment by xshuqun** [comment]
@jackhax1 Sorry for the late response. Apparently we are using at commands ATM$ to perform factory reset 
You can checkout the api here https://github.com/ambiot/ambd_matter/blob/main/component/common/application/matter/common/atcmd/atcmd_matter.c#L18
